apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nats
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  strategy: {}
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - image: nats:latest
        name: nats
        command: ["nats-server", "-c", "/etc/nats/nats-server.conf"]
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitor
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats/nats-server.conf
          subPath: nats-server.conf
        resources:
          requests:
            cpu: "150m"
            memory: "320Mi"
          limits:
            cpu: "400m"
            memory: "640Mi"
      volumes:
      - name: config-volume
        configMap:
          name: nats-config
status: {}
